repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.13
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.409
    hooks:
      - id: pyright
        additional_dependencies:
          - ldif
          - "adexplorersnapshot @ git+https://github.com/c3c/ADExplorerSnapshot.py.git"
